SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `API_KEY` (
  `id` binary(16) NOT NULL,
  `env` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `service_id` binary(16) NOT NULL,
  `user_id` binary(16) NOT NULL,
  `key_hash` varchar(255) NOT NULL,
  `key_prefix` varchar(255) NOT NULL,
  `expires_at` date DEFAULT NULL,
  `revoked_at` date DEFAULT NULL,
  `last_used_at` date DEFAULT NULL,
  `created_at` date NOT NULL,
  `updated_at` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `KEY_PERMISSION` (
  `key_id` binary(16) NOT NULL,
  `permission_id` binary(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PERMISSION` (
  `id` binary(16) NOT NULL,
  `url` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `method` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `service_id` binary(16) NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `deleted_at` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERVICE` (
  `id` binary(16) NOT NULL,
  `name` varchar(100) NOT NULL,
  `acronym` varchar(3) NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


ALTER TABLE `API_KEY`
  ADD PRIMARY KEY (`id`),
  ADD KEY `FK_KEY_SERVICE` (`service_id`),
  ADD KEY `key_prefix` (`key_prefix`);

ALTER TABLE `KEY_PERMISSION`
  ADD PRIMARY KEY (`key_id`,`permission_id`),
  ADD KEY `FK_Permission` (`permission_id`);

ALTER TABLE `PERMISSION`
  ADD PRIMARY KEY (`id`),
  ADD KEY `FK_PERMISSION_SERVICE` (`service_id`);

ALTER TABLE `SERVICE`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `API_KEY`
  ADD CONSTRAINT `FK_KEY_SERVICE` FOREIGN KEY (`service_id`) REFERENCES `SERVICE` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `KEY_PERMISSION`
  ADD CONSTRAINT `FK_Key` FOREIGN KEY (`key_id`) REFERENCES `API_KEY` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `FK_Permission` FOREIGN KEY (`permission_id`) REFERENCES `PERMISSION` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PERMISSION`
  ADD CONSTRAINT `FK_PERMISSION_SERVICE` FOREIGN KEY (`service_id`) REFERENCES `SERVICE` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
